name: encryption
description: "Encryption related utils"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  utils:
    path: "../utils"

  encryption_common:
    path: "../encryption_common"
  encryption_native:
    path: "../encryption_native"
  encryption_web:
    path: "../encryption_web"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
