targets:
  $default:
    builders:
      freezed:
        options:
          map: false
          when:
            when: false
            maybe_when: false
            when_or_null: false
        generate_for:
          include:
            - lib/model/freezed/**.dart
