name: encryption_web
description: "Encryption related utils implementation for native platforms"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  utils:
    path: "../utils"

  encryption_common:
    path: "../encryption_common"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
