name: encryption_web
description: "Encryption related utils implementation for native platforms"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  utils:
    path: "../utils"

  encryption_common:
    path: "../encryption_common"
