// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(BinaryDataResult2)>(isLeaf: true)
external void free_binary_data_result_2(BinaryDataResult2 result);

/// Generate a new message encryption keys.
///
/// Run equivalent free function for the result.
///
/// First result value is public key and second is private key.
@ffi.Native<BinaryDataResult2 Function(ffi.Pointer<ffi.Char>)>(isLeaf: true)
external BinaryDataResult2 generate_message_keys(ffi.Pointer<ffi.Char> account_id);

@ffi.Native<ffi.Void Function(BinaryDataResult)>(isLeaf: true)
external void free_binary_data_result(BinaryDataResult result);

/// Encrypt message data.
///
/// The result must be freed using free_binary_data_result.
///
/// First result value is PGP message and second is session key.
@ffi.Native<
  BinaryDataResult2 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>(isLeaf: true)
external BinaryDataResult2 encrypt_message(
  ffi.Pointer<ffi.Uint8> sender_private_key,
  int sender_private_key_len,
  ffi.Pointer<ffi.Uint8> recipient_public_key,
  int recipient_public_key_len,
  ffi.Pointer<ffi.Uint8> data,
  int data_len,
);

/// Decrypt message data.
///
/// The result must be freed using free_binary_data_result.
///
/// First result value is message data and second is session key.
@ffi.Native<
  BinaryDataResult2 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>(isLeaf: true)
external BinaryDataResult2 decrypt_message(
  ffi.Pointer<ffi.Uint8> sender_public_key,
  int sender_public_key_len,
  ffi.Pointer<ffi.Uint8> recipient_private_key,
  int recipient_private_key_len,
  ffi.Pointer<ffi.Uint8> pgp_message,
  int pgp_message_len,
);

/// Get message content from PGP message if possible.
///
/// The result must be freed using free_binary_data_result.
@ffi.Native<BinaryDataResult Function(ffi.Pointer<ffi.Uint8>, ffi.IntPtr)>(isLeaf: true)
external BinaryDataResult get_message_content(
  ffi.Pointer<ffi.Uint8> pgp_message,
  int pgp_message_len,
);

/// Message encryption API
final class BinaryData extends ffi.Struct {
  /// Null if failure
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.IntPtr()
  external int len;

  @ffi.IntPtr()
  external int capacity;
}

final class BinaryDataResult2 extends ffi.Struct {
  @ffi.IntPtr()
  external int result;

  /// Null if failure
  external BinaryData first_data;

  external BinaryData second_data;
}

final class BinaryDataResult extends ffi.Struct {
  @ffi.IntPtr()
  external int result;

  external BinaryData data;
}
