[package]
name = "rust_utils"
edition = "2021"
publish = false

[lib]
name = "rust_utils"
path = "src/lib.rs"
crate_type = ["staticlib"]

[profile.dev]
panic = "abort"
opt-level = 3

[profile.release]
panic = "abort"

[dependencies]
aes-gcm = "0.10.3"
pgp = "0.13.1"
smallvec = "1.13.2"
bstr = "1.10.0"
rand = "0.8.5"
