name: native_utils_ffi
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.13.0 <4.0.0'

resolution: workspace

dependencies:
  ffi: ^2.2.0
  hooks: ^2.0.0
  native_toolchain_rust: ^1.0.7

  native_utils_common:
    path: "../native_utils_common"

dev_dependencies:
  ffigen: ^19.0.0
