name: native_utils_ffi
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  ffi: ^2.1.2
  hooks: ^1.0.3
  native_toolchain_rust: ^1.0.4

  native_utils_common:
    path: "../native_utils_common"

dev_dependencies:
  ffigen: ^19.0.0
