name: database_provider
description: "Database provider"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  drift: ^2.26.0

  database_provider_native:
    path: "../database_provider_native"
  database_provider_web:
    path: "../database_provider_web"
  database:
    path: "../database"

dev_dependencies:
  lints: ^6.0.0
